# Reducción de los loops the álgebra matricial

Equipo 13 MNO

* Laura López 144089

* Dante Ruiz 183340

* José Carlos Escobar 175895

## Multiplicación de matrices

Definimos nuestros datos iniciales:

In [35]:
import numpy as np

In [86]:
A = np.random.rand(6,5)
print(A)

[[0.18196845 0.66955123 0.03647085 0.28999154 0.10105255]
 [0.23209573 0.82820277 0.32554872 0.01195396 0.92070555]
 [0.7218137  0.76111196 0.63573522 0.07968588 0.98324765]
 [0.39622858 0.66383259 0.51706209 0.06157722 0.33788983]
 [0.84609893 0.22335651 0.09383501 0.91544502 0.98032132]
 [0.44973483 0.19672672 0.51642563 0.0088567  0.08664754]]


In [87]:
B = np.random.rand(5,6)
print(B)

[[0.94287942 0.37852244 0.03231077 0.46416485 0.95204271 0.93652049]
 [0.93058291 0.30892748 0.99533548 0.36475209 0.27626976 0.83358469]
 [0.91327302 0.55803812 0.49832903 0.29414389 0.50739164 0.33346333]
 [0.79126367 0.76987143 0.69808079 0.01401811 0.95731922 0.8051149 ]
 [0.03985465 0.18279835 0.25657159 0.89898009 0.38295031 0.88016863]]


In [88]:
C = A.dot(B)
print(C)

[[1.06144227 0.53780248 0.91884686 0.43432061 0.69303608 1.06312633]
 [1.33301762 0.7028831  1.23864088 1.33344106 0.97898135 1.83629857]
 [2.07170041 1.1041995  1.40559    1.68469245 1.67285623 2.452019  ]
 [1.52575619 0.75277014 1.06088443 0.88275978 1.01132046 1.44383488]
 [1.85474676 1.325608   1.18699067 1.39592229 2.16662753 2.60975259]
 [1.08921512 0.54185175 0.49610423 0.51042959 0.78620684 0.84077838]]


In [89]:
print(A.shape)
print(B.shape)
print(C.shape)

(6, 5)
(5, 6)
(6, 6)


**Versión i,j,k**

In [95]:
# Multiplicar el primer renglón de a por la matriz de b
num_renglones_de_A = A.shape[0]
for i in range(0,num_renglones_de_A):
    print(A[i].dot(B))

[1.06144227 0.53780248 0.91884686 0.43432061 0.69303608 1.06312633]
[1.33301762 0.7028831  1.23864088 1.33344106 0.97898135 1.83629857]
[2.07170041 1.1041995  1.40559    1.68469245 1.67285623 2.452019  ]
[1.52575619 0.75277014 1.06088443 0.88275978 1.01132046 1.44383488]
[1.85474676 1.325608   1.18699067 1.39592229 2.16662753 2.60975259]
[1.08921512 0.54185175 0.49610423 0.51042959 0.78620684 0.84077838]


**Versión k,i,j**

In [101]:
# Colummna i de A
# Fila i de B
D = np.zeros((6,6))
for i in range(0,5):
    D = D + np.outer(A[:,[i]],B[i])

print(D)

[[1.06144227 0.53780248 0.91884686 0.43432061 0.69303608 1.06312633]
 [1.33301762 0.7028831  1.23864088 1.33344106 0.97898135 1.83629857]
 [2.07170041 1.1041995  1.40559    1.68469245 1.67285623 2.452019  ]
 [1.52575619 0.75277014 1.06088443 0.88275978 1.01132046 1.44383488]
 [1.85474676 1.325608   1.18699067 1.39592229 2.16662753 2.60975259]
 [1.08921512 0.54185175 0.49610423 0.51042959 0.78620684 0.84077838]]


**Versión ikj**

In [102]:
# Multiplicar el primer renglón de a por la matriz de b
num_renglones_de_A = A.shape[0]
for i in range(0,num_renglones_de_A):
    print(A[i].dot(B))

[1.06144227 0.53780248 0.91884686 0.43432061 0.69303608 1.06312633]
[1.33301762 0.7028831  1.23864088 1.33344106 0.97898135 1.83629857]
[2.07170041 1.1041995  1.40559    1.68469245 1.67285623 2.452019  ]
[1.52575619 0.75277014 1.06088443 0.88275978 1.01132046 1.44383488]
[1.85474676 1.325608   1.18699067 1.39592229 2.16662753 2.60975259]
[1.08921512 0.54185175 0.49610423 0.51042959 0.78620684 0.84077838]


## Método de sustitución hacia atras

Definimos el sistema de ecuaciones de 4 x 4

In [140]:
E = np.array([[4,-1,2,3],[0,-2,7,-4],[0,0,6,5],[0,0,0,3]])
print(E)

[[ 4 -1  2  3]
 [ 0 -2  7 -4]
 [ 0  0  6  5]
 [ 0  0  0  3]]


In [139]:
b = np.array([[20],[-7],[4],[6]])
print(b)

[[20]
 [-7]
 [ 4]
 [ 6]]


Checamos que la diagonal sea diferente de cero

In [132]:
np.sum(np.diag(E) != 0)

4

Ejecutamos el algorítmo

In [198]:
# Inicializamos un vector de ceros de 4x1 donde ponemos las respuestas
x = np.zeros((4,1))

# Calculamos x_n
x[3] = b[3] / E[3][3]
# Calculamos x_n_1 hasta 1
n = 4
for i in range(n-1,-1,-1):
     x[i] = ( b[i] - E[i,(i+1):n].dot(x[(i+1):n]) ) / E[i,i]

print(x)

[[ 3.]
 [-4.]
 [-1.]
 [ 2.]]


Verificamos que la respuesta este bien con la función de python.

In [183]:
np.linalg.solve(E,b)

array([[ 3.],
       [-4.],
       [-1.],
       [ 2.]])